### ISSUE TITLE
Support for other devices!

### ISSUE THREAD

**Issue by AbdelrahmanBerchan** [YehiaWLD/Ball-Run#2]
Dear @YehiaWLD,

There is no support for mac, this will limit mac users like me to use and play your game!
Pls fix this problem.

Thank you

**Comment by YehiaWLD** [comment]
i am currently working on a **mac os** and **linux build** and it is in the beta testing phase!
hopefully expect it to come sometime this week!

**Comment by YehiaWLD** [comment]
![image](https://user-images.githubusercontent.com/66638625/212543875-a7c92e9d-3ff2-4fe3-b89d-f9451d5e4fdb.png)
i also stated in the readme that i am working on it

**Comment by YehiaWLD** [comment]
Mack version boutta be released!

**Comment by AbdelrahmanBerchan** [comment]
ok cool
